[package]
name = "steam-optionx"
version = "0.1.0"
edition = "2024"

[dependencies]
confy = "1.0.0"
directories = "6.0.0"
keyvalues-serde = "0.2.2"
reqwest = { version = "0.12.19", features = ["blocking", "json"] }
rfd = "0.15.3"
serde = { version = "1.0.219", features = ["derive"] }
serde-value = "0.7.0"
slint = "1.11.0"
